export const prompts_tour_box = [
    "What are some must-see attractions in Paris?",
    "How can I find budget-friendly accommodation while traveling?",
    "What are the top safety tips for solo travelers?",
    "Can you recommend some off-the-beaten-path destinations in Europe?",
    "What are the best times of year to visit national parks in the United States?",
    "How do cultural differences impact tourism experiences?",
    "What are some eco-friendly travel tips?",
    "How can I avoid common tourist scams?",
    "What are the benefits of guided tours?",
    "How do I plan a memorable honeymoon trip?",
    "What are the most popular tourist attractions in New York City?",
    "What are the essentials to pack for a beach vacation?",
    "How do I stay healthy while traveling?",
    "What are some unique food experiences around the world?",
    "How can I find local cultural festivals while traveling?",
    "What are the advantages of traveling in a group?",
    "How do I handle language barriers while traveling?",
    "What are some good travel apps to use?",
    "How do I choose the right travel insurance?",
    "What are the etiquette rules in different countries?",
    "How can I travel responsibly?",
    "What are the best ways to save money on flights?",
    "How can I make the most of a short trip?",
    "What are some underrated cities to visit?",
    "How do I plan a backpacking trip across Europe?",
    "What are the benefits of staying in hostels?",
    "How can I meet other travelers while on the road?",
    "What are the best travel destinations for adventure seekers?",
    "How do I find local transportation options abroad?",
    "What are the benefits of cultural exchange programs?",
    "How can I travel sustainably?",
    "What are the best travel destinations for history buffs?",
    "How can I avoid over-tourism in popular destinations?",
    "What are some etiquette tips for visiting religious sites?",
    "How do I navigate local markets while traveling?",
    "What are the most scenic road trips to take?",
    "How can I support local communities while traveling?",
    "What are the best destinations for food lovers?",
    "How do I handle jet lag effectively?",
    "What are the benefits of travel blogging?",
    "How do I choose the right travel guidebooks?",
    "What are some free activities to do while traveling?",
    "How can I find authentic local experiences?",
    "What are the benefits of solo travel?",
    "How do I respect wildlife while traveling?",
    "What are some travel safety tips for families?",
    "How can I learn about local history while traveling?",
    "What are the best travel destinations for photography?",
    "How do I travel with pets?",
];

export const prompts_idea_box = [
    "How can we improve recycling processes in urban areas?",
    "What are some innovative ways to use renewable energy sources?",
    "Can you suggest new ideas for reducing plastic waste?",
    "How might virtual reality be used to enhance education?",
    "What are some creative solutions to urban traffic congestion?",
    "How can technology be leveraged to improve healthcare in remote areas?",
    "What are innovative ways to encourage sustainable agriculture?",
    "How can AI be used to personalize online shopping experiences?",
    "What are some futuristic transportation concepts?",
    "How might blockchain revolutionize supply chain management?",
    "What are innovative solutions for reducing food waste?",
    "How can we harness solar energy more effectively?",
    "What are some unique ideas for affordable housing?",
    "How can we combat climate change through innovation?",
    "What are some innovative ideas for smart cities?",
    "How can we improve water purification techniques?",
    "What are new approaches to disaster relief?",
    "How might wearable technology change healthcare?",
    "What are innovative ways to promote gender equality?",
    "How can we improve access to clean drinking water globally?",
    "What are some creative uses of 3D printing technology?",
    "How can AI enhance cybersecurity?",
    "What are innovative ways to reduce air pollution?",
    "How can we improve access to education in developing countries?",
    "What are some innovative ideas for space exploration?",
    "How might drones be used for social good?",
    "What are creative solutions for reducing healthcare costs?",
    "How can we promote sustainable fashion?",
    "What are innovative approaches to recycling electronics?",
    "How might biotechnology revolutionize medicine?",
    "What are some unique ideas for urban gardening?",
    "How can we use technology to enhance cultural preservation?",
    "What are innovative solutions for improving mental health care?",
    "How might augmented reality be used in entertainment?",
    "What are new ideas for reducing carbon emissions?",
    "How can we improve global internet connectivity?",
    "What are some innovative ways to promote diversity in the workplace?",
    "How can we improve battery storage technology?",
    "What are creative solutions for reducing noise pollution?",
    "How might AI be used for wildlife conservation?",
    "What are innovative ideas for reducing poverty?",
    "How can we enhance disaster preparedness?",
    "What are new approaches to sustainable tourism?",
    "How might blockchain improve voting systems?",
    "What are innovative ideas for reducing healthcare disparities?",
    "How can we improve waste management practices?",
    "What are some unique ideas for eco-friendly architecture?",
];

export const prompts_college_box = [
    "What are the benefits of joining student clubs and organizations?",
    "How can networking benefit college students?",
    "What are effective strategies for building professional relationships in college?",
    "How can LinkedIn be used effectively for networking?",
    "What are the advantages of attending college career fairs?",
    "How do internships help in building a professional network?",
    "What are some tips for successful alumni networking?",
    "How can college alumni networks support career development?",
    "What are the benefits of mentorship programs in college?",
    "How does participating in college events contribute to networking?",
    "What are the best ways to find a mentor in college?",
    "How can volunteering enhance networking opportunities?",
    "What are the benefits of studying abroad for networking?",
    "How can social media be used for professional networking?",
    "What are effective networking strategies for introverted students?",
    "How can college students build relationships with professors?",
    "What are the advantages of joining honor societies?",
    "How can part-time jobs in college help with networking?",
    "What are some networking mistakes to avoid in college?",
    "How can college students network during summer breaks?",
    "What are the benefits of joining academic organizations?",
    "How can attending workshops and conferences enhance networking?",
    "What are some tips for effective elevator pitches?",
    "How can college students network within their community?",
    "What are the benefits of informational interviews?",
    "How can college students build a network in their field of interest?",
    "What are effective networking strategies for graduate students?",
    "How can LinkedIn endorsements strengthen a student's network?",
    "What are the benefits of joining online networking groups?",
    "How can college students network with alumni in different industries?",
    "What are some networking opportunities in college beyond career services?",
    "How can college students use networking to explore career options?",
    "What are effective networking strategies for international students?",
    "How can college students leverage their hobbies for networking?",
    "What are the benefits of attending industry-specific networking events?",
    "How can college students network with professionals at conferences?",
    "What are some networking tips for attending job fairs?",
    "How can volunteering enhance networking opportunities in college?",
    "What are the benefits of peer-to-peer networking in college?",
    "How can college students network with recruiters on campus?",
    "What are the advantages of participating in study groups for networking?",
    "How can college students network with local businesses?",
    "What are some online platforms for college networking?",
    "How can college students use LinkedIn groups for networking?",
    "What are the benefits of building a diverse network in college?",
    "How can college students network with professors outside of class?",
    "What are effective networking strategies for first-year college students?",
];

export const prompts_coding_box = [
    "What are the basic principles of object-oriented programming?",
    "How do you write a simple 'Hello, World!' program in Python?",
    "What are the differences between front-end and back-end development?",
    "What is version control and why is it important in programming?",
    "How do you handle errors and exceptions in programming?",
    "What are the benefits of using frameworks in web development?",
    "How can you optimize code for better performance?",
    "What are some common data structures used in programming?",
    "How does functional programming differ from object-oriented programming?",
    "What are some best practices for secure coding?",
    "What are the differences between Java and JavaScript?",
    "How do you use APIs in web development?",
    "What are the advantages of using cloud computing in programming?",
    "How can you improve code readability?",
    "What are the steps to debug a program?",
    "How does asynchronous programming work?",
    "What are the benefits of test-driven development?",
    "How can you effectively manage dependencies in a project?",
    "What are some popular programming paradigms?",
    "How do you handle file operations in programming?",
    "What are the principles of clean code?",
    "How can you implement data validation in your applications?",
    "What are some ways to optimize database queries?",
    "How do you deploy a web application?",
    "What are the advantages of using microservices architecture?",
    "How can you implement authentication and authorization in a web application?",
    "What are the benefits of using design patterns in programming?",
    "How do you use recursion in programming?",
    "What are some strategies for code refactoring?",
    "How can you integrate third-party libraries in your project?",
    "What are the principles of responsive web design?",
    "How do you handle sessions and cookies in web development?",
    "What are the basics of SQL and database management?",
    "How can you improve user experience in a web application?",
    "What are some tools for continuous integration and continuous deployment?",
    "How do you use regular expressions in programming?",
    "What are the principles of scalable software architecture?",
    "How can you optimize frontend performance?",
    "What are some techniques for data serialization?",
    "How do you implement error handling in RESTful APIs?",
    "What are the advantages of using containers in software development?",
    "How can you implement caching in your applications?",
    "What are the principles of object-relational mapping (ORM)?",
    "How do you manage state in frontend frameworks?",
    "What are some strategies for versioning APIs?",
    "How can you secure sensitive data in your applications?",
    "What are the principles of network programming?",
    "How do you handle cross-browser compatibility issues in web development?",
    "How can you monitor application performance?",
];

